### ISSUE TITLE
Error: could not find root process

### ISSUE THREAD

**Issue by fyqls** [VerizonMedia/kubectl-flame#38]
$ ./kubectl-flame -n PythonPod -l python -f /tmp/python.svg
Verifying target pod ... ✔
Launching profiler ... ✔
Profiling ... Error: could not find root process

**Comment by edeNFed** [comment]
Hi @fyqls,
Can you please give some more details about the container image you are trying to profile?
The current logic for finding the python process is searching for a process named `python` which wasn't created by other python processes.

**Comment by italux** [comment]
Hey, @edeNFed I'm facing the same issue with a python container application running on an AKS cluster.

The application I'm trying to inspect doesn't start with `python` command, since is a web application and we use `uwsgi` to start the webserver. As an attempt to get the flame job working I used the `--pgrep` param to tell flame job the right process name but I get the same error.

```
kubectl flame -n namespace pod-uuid -t 1m --lang python -f /tmp/flamegraph.svg python-container -p uwsgi
Verifying target pod ... ✔
Launching profiler ... ❌
2021/02/20 14:17:52 pod failed
```
- Flame Job logs
```
kubectl -n namespace logs kubectl-flame-c8b83ed4-c3c4-495a-9c9b-a996e1f4c584-kqqf5
{"type":"progress","data":{"time":"2021-02-20T17:17:52.596068414Z","stage":"started"}}
{"type":"error","data":{"reason":"could not find root process"}}
```
Looking at the `--dry-run` job output below we can realize (comparing with a java job) that we don't have the default profiling event string set to `wall`, see:
```apiVersion: batch/v1
[...]
    spec:
      containers:
      - args:
        - 60439b22-ce6e-4c59-ad67-6278747ff98b
        - e1014577-95c4-4789-9b3f-dc295a3a5c2d
        - python-container
        - docker://54c7e7b24647e8f258e8a6ca454e16fa012b434cb2d1e4250c25861d3bafc107
        - 1m0s
        - python
        - uwsgi
        command:
        - /app/agent
        image: verizondigital/kubectl-flame:v0.1.9-python
```
When I explicit add the `-e wall` to the command I get the job launched correctly, see the outputs below:
- Flame job dry-run
```
    spec:
      containers:
      - args:
        - 8d46d442-1c81-4b0c-9605-d6787390103e
        - e1014577-95c4-4789-9b3f-dc295a3a5c2d
        - loggiweb
        - docker://54c7e7b24647e8f258e8a6ca454e16fa012b434cb2d1e4250c25861d3bafc107
        - 1m0s
        - java
        - wall
        - uwsgi
        command:
        - /app/agent
        image: verizondigital/kubectl-flame:v0.1.9-jvm
```
```
kubectl flame -n namespace pod-uuid -t 1m --lang python -f /tmp/flamegraph.svg python-container -p uwsgi -e wall
Verifying target pod ... ✔
Launching profiler ... ✔
```

**Comment by italux** [comment]
Hey, @edeNFed I'm facing the same issue with a python container application running on an AKS cluster.

The application I'm trying to inspect doesn't start with `python` command, since is a web application and we use `uwsgi` to start the webserver. As an attempt to get the flame job working I used the `--pgrep` param to tell flame job the right process name but I get the same error.

```
kubectl flame -n namespace pod-uuid -t 1m --lang python -f /tmp/flamegraph.svg python-container -p uwsgi
Verifying target pod ... ✔
Launching profiler ... ❌
2021/02/20 14:17:52 pod failed
```
- Flame Job logs
```
kubectl -n namespace logs kubectl-flame-c8b83ed4-c3c4-495a-9c9b-a996e1f4c584-kqqf5
{"type":"progress","data":{"time":"2021-02-20T17:17:52.596068414Z","stage":"started"}}
{"type":"error","data":{"reason":"could not find root process"}}
```
- Flame job `dry-run`
```apiVersion: batch/v1
[...]
    spec:
      containers:
      - args:
        - 60439b22-ce6e-4c59-ad67-6278747ff98b
        - e1014577-95c4-4789-9b3f-dc295a3a5c2d
        - python-container
        - docker://54c7e7b24647e8f258e8a6ca454e16fa012b434cb2d1e4250c25861d3bafc107
        - 1m0s
        - python
        - uwsgi
        command:
        - /app/agent
        image: verizondigital/kubectl-flame:v0.1.9-python
```

**Comment by italux** [comment]
@edeNFed I've realized that the issue happens because the python profile job doesn't add the host volumes into the job templates the #42 is my proposal to fix it, when possible could you please take a look into the PR?

This is the output with the patch applied:
```
./kube-flame -n namespace pod-name -t 2m --lang python -f /tmp/flamegraph.svg container-name --image verizondigital/kubectl-flame:v0.1.9-python -p uwsgi --dry-run
Verifying target pod ... ✔
Launching profiler ... ✔
Profiling ... ✔
FlameGraph saved to: /tmp/flamegraph.svg 🔥
```
```
./kube-flame -n namespace pod-name -t 2m --lang python -f /tmp/flamegraph.svg container-name --image verizondigital/kubectl-flame:v0.1.9-python -p uwsgi --dry-run
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  creationTimestamp: null
  labels:
    kubectl-flame/id: cdc7e0f7-2176-4c15-8578-a1b5cbe5e923
  name: kubectl-flame-cdc7e0f7-2176-4c15-8578-a1b5cbe5e923
  namespace: namespace
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        kubectl-flame/id: cdc7e0f7-2176-4c15-8578-a1b5cbe5e923
      name: kubectl-flame-cdc7e0f7-2176-4c15-8578-a1b5cbe5e923
      namespace: namespace
    spec:
      containers:
      - args:
        - cdc7e0f7-2176-4c15-8578-a1b5cbe5e923
        - ee0b67a4-2a17-438b-92d0-c331aca0fa6d
        - container-name
        - docker://19f64538c4e364fbf83e18b7e2c5260fa27bf079f725abb62fe6777573e4ab36
        - 2m0s
        - python
        - uwsgi
        command:
        - /app/agent
        image: verizondigital/kubectl-flame:v0.1.9-python
        imagePullPolicy: Always
        name: kubectl-flame
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/docker
          name: target-filesystem
      hostPID: true
      nodeName: node-0001
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /var/lib/docker/
        name: target-filesystem
  ttlSecondsAfterFinished: 5
status: {}
```
